import { HeadSection } from "../../components/head_section";
import { Cell, Row } from "../../components/row_and_cell";

export function DetalleAccidente() {
  return (
    <>
      <HeadSection label="1. FECHA, HORA Y UBICACIÓN" />
      <Row>
        <Cell
          width={33.3}
          label="Fecha:"
          value="11/03/2023"
          inline
          width_head={50}
          width_content={50}
        />
        <Cell
          width={33.3}
          label="Hora:"
          value="11/03/2023"
          inline
          width_head={50}
          width_content={50}
        />
        <Cell
          width={33.4}
          label="Turno:"
          value="11/03/2023"
          inline
          width_head={50}
          width_content={50}
        />
      </Row>
      <Row>
        <Cell
          width={100}
          label="Unidad:"
          value="11/03/2023"
          inline
          width_head={16.6}
          width_content={83.4}
        />
      </Row>
      <Row>
        <Cell
          width={100}
          label="Área:"
          value="11/03/2023"
          inline
          width_head={16.6}
          width_content={83.4}
        />
      </Row>
      <Row>
        <Cell
          width={40}
          label="Labor:"
          value="11/03/2023"
          inline
          width_head={41.5}
          width_content={58.5}
        />
        <Cell
          width={20}
          label="Nivel:"
          value="11/03/2023"
          inline
          width_head={40}
          width_content={60}
        />
        <Cell
          width={20}
          label="Mina:"
          value="11/03/2023"
          inline
          width_head={40}
          width_content={60}
        />
        <Cell
          width={20}
          label="Zona:"
          value="11/03/2023"
          inline
          width_head={40}
          width_content={60}
        />
      </Row>
      <Row>
        <Cell
          width={100}
          label="Lugar:"
          value="11/03/2023"
          inline
          width_head={16.6}
          width_content={83.4}
        />
      </Row>

      <HeadSection label="2. CLASIFIACIÓN DEL INCIDENTE / ACCIDENTE" />
      <Row>
        <Cell
          width={33.3}
          label="Clasificación:"
          value="11/03/2023"
          inline
          width_head={50}
          width_content={50}
        />
        <Cell
          width={33.3}
          label="Tipo:"
          value="11/03/2023"
          inline
          width_head={50}
          width_content={50}
        />
        <Cell
          width={33.4}
          label="Sistema:"
          value="11/03/2023"
          inline
          width_head={50}
          width_content={50}
        />
      </Row>
      <Row>
        <Cell
          width={60}
          label="Tipo de Accidente (Tabla 10 de Anexo N° 31):"
          value="11/03/2023"
        />
        <Cell width={40} label="Lesión_Anatómica:" value="11/03/2023" />
      </Row>
    </>
  );
}
